fix for missing message:
Top level Sentry exception caught - failed creating log record
Response:
%s
Traceback (most recent call last):
  File /home/deploy/.virtualenvs/pound/src/sterling/sterling/logging/sentry/handlers.py, line 40, in emit
    return self._emit(record)
  File /home/deploy/.virtualenvs/pound/src/sterling/sterling/logging/sentry/handlers.py, line 81, in _emit
    data=data, extra=extra, date=date, **kwargs)
  File /home/deploy/.virtualenvs/pound/src/raven/raven/base.py, line 227, in capture
    data['message'] = handler.to_string(data)
  File /home/deploy/.virtualenvs/pound/src/raven/raven/events.py, line 108, in to_string
    return msg['message'] % tuple(msg.get('params', ()))
TypeError: not all arguments converted during string formatting